#!/usr/bin/python

from monop.gameconf import GameConf
from monop.dice import Dice
from monop.model import Model

def main(argv):
	EXIT_SUCCESS = 0
	EXIT_FAILURE = 1

	c = GameConf(open(argv[1]))
	d = Dice()


	rj = Model(c, d, rj = True)
	rj.print_tables()
	print
	lj = Model(c, d, rj = False)
	lj.print_tables()

	return EXIT_SUCCESS

if __name__ == '__main__':
	from sys import argv
	raise SystemExit, main(argv)
