#!/usr/bin/python

from argparse import ArgumentParser
from monop.gameconf import GameConf
from monop.gamestate import GameState
from monop.player import Player
from monop.dice import Dice
from monop.model import Model
from monop.simplestrategy import SimpleStrategy
from copy import copy
import sys

def game_from_conf(c, player):
	gs = GameState()
	enemy = Player()
	enemy.name = 'Enemy'
	enemy.playerid = player.playerid + 1
	gs.game_init([player, enemy])

	for i, e in enumerate(c.estates):
		e = copy(e)
		try:
			g = c.groups[e.group]
		except KeyError:
			g = None
		if g is not None and g.houseprice >= 0:
			e.houseprice = g.houseprice
		e.estateid = i
		gs.estates[i] = e
	for i, g in enumerate(c.groups):
		g = copy(g)
		g.groupid = i
		gs.groups[g.groupid] = g
	gs.game_on()
	return gs

def main():
	opts = ArgumentParser(description='Test a game strategy')
	opts.add_argument('cash', metavar='cash', type=int,
				help = 'Amount of cash')
	opts.add_argument('properties', metavar='property', type=int,
				nargs='+',
				help = 'Properties owned')
	opts.add_argument('--config',
				metavar = 'config',
				type = str,
				default = './configs/london.conf',
				help = 'monopd config file')
	opts.add_argument('--print-tables',
				action = 'store_true',
				default = False,
				help = 'Print statistics tables')
	opts.add_argument('--rij',
				action = 'store_true',
				default = False,
				help = 'Remain-in-jail model')

	args = opts.parse_args()

	print 'Loading config fromm: %s'%args.config
	c = GameConf(open(args.config))
	d = Dice()

	print 'Using %s strategy'%(args.rij and 'remain-in-jail' \
					or 'leave-jail')

	m = Model(c, d, rj = args.rij)
	if args.print_tables:
		m.print_tables()

	p= Player()
	p.playerid = 0
	p.name = 'player'
	p.money = args.cash
	gs = game_from_conf(c, p)

	s = SimpleStrategy()
	def strategy_msg(it, msg, tags):
		color = {
			'default':0,
			'dark red':1,
			'dark green':2,
			'dark yellow':3,
			'dark blue':4,
			'dark magenta':5,
			'dark cyan':6,
			'light gray':7,
			'light grey':7,
			'dark gray':8,
			'dark grey':8,
			'red':9,
			'green':10,
			'yellow':11,
			'blue':12,
			'magenta':13,
			'cyan':14,
			'white':15,
		}
		b = False
		c = color['default']
		for t in tags:
			if t == 'bold':
				b = True
			c = color.get(t, c)
		sys.stdout.write('\033[%u;%dm%s\033[0m'%(b, 30 + c, msg))
	m = []
	def mortgage(it, estateid):
		m.append(('mortgage', estateid))
	def unmortgage(it, estateid):
		m.append(('unmortgage', estateid))
	def buy_house(it, estateid):
		m.append(('buy-house', estateid))
	def sell_house(it, estateid):
		m.append(('sell-house', estateid))
	s.connect('msg', strategy_msg)
	s.connect('mortgage', mortgage)
	s.connect('unmortgage', unmortgage)
	s.connect('buy-house', buy_house)
	s.connect('sell-house', sell_house)
	s.game_on(gs)
	
	print
	print 'Cash amount: %d'%args.cash
	print 'Properties owned: %s'%(', '.join(map(str, args.properties)))
	for e in map(lambda x:gs.estates[x], args.properties):
		e.owner = p.playerid
		print ' - ', e.name
	print

	print 'Simulating:'
	s.manage_estates(p)
	print

	print 'Solution:'
	for (move, estateid) in m:
		e = c.estates[estateid]
		g = c.groups[e.group]
		print move, estateid, e.name
		if move == 'buy-house':
			p.money -= g.houseprice
	print
	
	print 'Cash remaining: %u'%p.money
	
if __name__ == '__main__':
	main()
	raise SystemExit, 0
